[package]
name = "links-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = {version = "0.8.5"}
num-bigint = { version = "0.4.3",  features = ["rand"] }
zeroize = { version = "1.5" }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
serde_jcs = { version = "0.1", default-features = false }
num-prime = "0.4.3"
num-integer = "0.1.45"
rug = "1.19.2"

# rust-gmp = "0.5.0"

# gmp-mpfr-sys = "1.5"
glass_pumpkin = "1.5.0"

num-primes = "0.3.0"


[lib]
name = "links_crypto"
path = "src/lib.rs"

[[bin]]
name = "demo"
path = "src/main.rs"
