[package]
name = "zkryptium"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = {version = "0.8.5"}
zeroize = { version = "1.5" }
serde = { version = "1.0.25", default_feature = false, features = ["derive", "serde_derive"] }
serde_json = "1.0.59"
hex = "0.4.3"

# cl03
rug = { version = "1.19.2", features = ["serde"]}


sha3 = "0.10.8"
sha2 = "0.10.6"
hkdf = "0.12.3"
digest = "0.10.6"

# bbsplus
bls12_381_plus = "0.8.5"
ff = "0.13.0"
group = "0.10"
elliptic-curve = "0.13.4"


cargo-license = "0.5.1"
log = "0.4.0"
env_logger = "0.10.0"
dotenv = "0.15.0"


[lib]
name = "zkryptium"
path = "src/lib.rs"

[[example]]
name = "bbsplus"
path = "examples/bbsplus.rs"

[[example]]
name = "cl03"
path = "examples/cl03.rs"

